export interface Brand {
  id: string;
  name: string;
  category: string;
  logo: string;
  description: string;
}

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  description: string;
  moq: string;
  priceRange: string;
  image: string;
  upc: string;
  sku: string;
  specs: { label: string; value: string }[];
  features: string[];
  certifications: string[];
  availability: string;
}

export const brands: Brand[] = [
  { id: "weathertech", name: "WeatherTech", category: "Interior Accessories", logo: "WT", description: "Custom-fit floor liners, cargo liners, and vehicle protection products made in USA" },
  { id: "amsoil", name: "AMSOIL", category: "Fluids & Lubricants", logo: "AM", description: "Premium synthetic motor oils, lubricants, and filtration products" },
  { id: "meguiars", name: "Meguiar's", category: "Detailing & Car Care", logo: "MG", description: "Professional-grade car care, waxes, polishes, and detailing products" },
  { id: "thule", name: "Thule", category: "Roof Racks & Cargo", logo: "TH", description: "Premium roof racks, bike carriers, cargo boxes, and outdoor adventure gear" },
  { id: "brembo", name: "Brembo", category: "Brakes", logo: "BR", description: "High-performance brake systems and premium ceramic brake pads" },
  { id: "noco", name: "NOCO", category: "Tools & Accessories", logo: "NC", description: "Portable lithium jump starters, battery chargers, and smart power solutions" },
  { id: "kn", name: "K&N", category: "Filters", logo: "KN", description: "High-performance washable air filters, intake systems, and filtration products" },
  { id: "bosch", name: "Bosch", category: "Wipers", logo: "BO", description: "Premium wiper blades, auto parts, and automotive technology" },
  { id: "sparco", name: "Sparco", category: "Racing & Interior", logo: "SP", description: "Racing-inspired steering wheel covers, accessories, and motorsport gear" },
  { id: "recaro", name: "Recaro", category: "Seats", logo: "RC", description: "Premium racing seats, ergonomic sport seats, and safety-focused seating" },
];

export const products: Product[] = [
  {
    id: "weathertech-floorliner-444751",
    name: "WeatherTech FloorLiner DigitalFit (Front Row - Black)",
    brand: "WeatherTech",
    category: "Interior Accessories",
    description: "Laser-measured floor liners with advanced surface channels that trap fluids, mud, and debris. Custom-fit for Ford F-150 (select cab models). Made in USA from patented high-density thermoplastic.",
    moq: "20 sets",
    priceRange: "Contact for pricing",
    image: "interior",
    upc: "787765362145",
    sku: "444751",
    specs: [
      { label: "Compatibility", value: "Ford F-150 (select cab models)" },
      { label: "Material", value: "Patented high-density TPO thermoplastic" },
      { label: "Design", value: "Advanced channels retain fluids, mud, and sand" },
      { label: "Fit", value: "Digital laser measurement for perfect floor coverage" },
      { label: "Color", value: "Black" },
      { label: "Made In", value: "USA" },
    ],
    features: ["Digital Laser Fit", "Advanced Channel Design", "High-Density TPO", "Made in USA", "All-Weather Protection"],
    certifications: ["ISO 9001", "OE Spec"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "amsoil-signature-5w30-aslqt",
    name: "AMSOIL Signature Series 5W-30 Synthetic Motor Oil (1 Qt)",
    brand: "AMSOIL",
    category: "Fluids & Lubricants",
    description: "100% synthetic motor oil delivering 75% more protection against power loss and engine wear than industry standards. Superior viscosity control across extreme temperatures.",
    moq: "48 quarts",
    priceRange: "Contact for pricing",
    image: "fluids",
    upc: "097012013017",
    sku: "ASLQT-EA",
    specs: [
      { label: "Viscosity", value: "5W-30" },
      { label: "Type", value: "100% full synthetic" },
      { label: "Certifications", value: "API SP, SN Plus, ILSAC GF-6A, GM dexos1 Gen 3" },
      { label: "Protection", value: "75% more wear protection vs. industry standard" },
      { label: "Volume", value: "1 quart (946 ml)" },
      { label: "Temp Range", value: "Excellent viscosity control in extreme temperatures" },
    ],
    features: ["Signature Series", "API SP Certified", "Dexos1 Gen 3", "Extreme Temp Performance", "Extended Drain"],
    certifications: ["API SP", "ILSAC GF-6A", "GM dexos1 Gen 3"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "meguiars-ultimate-wax-g18216",
    name: "Meguiar's Ultimate Liquid Wax (Synthetic - 16 oz)",
    brand: "Meguiar's",
    category: "Detailing & Car Care",
    description: "Pure synthetic polymer wax with ThinFilm technology. Apply in direct sun or shade with no white residue on trim. Maximum hydrophobic protection that enhances reflection and color depth.",
    moq: "24 units",
    priceRange: "Contact for pricing",
    image: "detailing",
    upc: "070382005405",
    sku: "G18216",
    specs: [
      { label: "Formula", value: "Pure Synthetic Polymer (ThinFilm technology)" },
      { label: "Application", value: "Sun or shade — no white residue on plastics" },
      { label: "Protection", value: "Maximum hydrophobic water beading" },
      { label: "Finish", value: "Enhances reflection and color depth" },
      { label: "Includes", value: "Foam applicator pad and microfiber towel" },
      { label: "Size", value: "16 oz (473 ml)" },
    ],
    features: ["ThinFilm Technology", "Sun or Shade Application", "Hydrophobic Protection", "No White Residue", "Includes Applicator Kit"],
    certifications: ["ISO 9001"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "thule-proride-xt-598004",
    name: "Thule ProRide XT Roof Bike Carrier",
    brand: "Thule",
    category: "Roof Racks & Cargo",
    description: "Premium roof-mounted bike carrier with torque-limiting knob for safe frame grip. Fits round frames up to 80 mm and oval frames up to 80 x 100 mm. Compatible with Thule WingBar, AeroBlade, and T-track bars.",
    moq: "12 units",
    priceRange: "Contact for pricing",
    image: "cargo",
    upc: "091021495941",
    sku: "598004",
    specs: [
      { label: "Capacity", value: "1 bicycle up to 20 kg (44 lbs)" },
      { label: "Torque Mechanism", value: "Torque-limiting knob for safe frame force" },
      { label: "Frame Compatibility", value: "Round up to 80 mm, oval up to 80 x 100 mm" },
      { label: "Mounting", value: "Fits Thule WingBar, AeroBlade, and T-track bars" },
      { label: "Security", value: "Lockable bike-to-carrier and carrier-to-rack" },
      { label: "Color", value: "Silver/Black" },
    ],
    features: ["Torque-Limiting Knob", "Frame Protection", "One-Hand Operation", "Lockable", "T-Track Compatible"],
    certifications: ["ISO 9001", "TUV/GS"],
    availability: "In Stock — Ships within 7 days",
  },
  {
    id: "brembo-ceramic-p85144n",
    name: "Brembo Premium Ceramic Brake Pads (Front Axle)",
    brand: "Brembo",
    category: "Brakes",
    description: "Advanced ceramic compound brake pads engineered to minimize brake dust. Thermally stable braking with reduced noise and vibration via multi-layer shims. OE-compliant for select Audi and Volkswagen models.",
    moq: "30 sets",
    priceRange: "Contact for pricing",
    image: "brakes",
    upc: "8020584067345",
    sku: "P85144N",
    specs: [
      { label: "Material", value: "Advanced ceramic compound" },
      { label: "Performance", value: "Thermally stable, reduced noise and vibration" },
      { label: "Shims", value: "Multi-layer noise-dampening shims" },
      { label: "Compatibility", value: "Select Audi A3, Q3 / VW Golf, Jetta, Tiguan" },
      { label: "Certification", value: "OE (Original Equipment) compliant" },
      { label: "Dust", value: "Minimized brake dust formulation" },
    ],
    features: ["Advanced Ceramic", "Low Dust", "Multi-Layer Shims", "OE Compliant", "Thermally Stable"],
    certifications: ["SAE", "ISO 9001", "OE Spec"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "noco-genius-gb40",
    name: "NOCO Genius GB40 Boost Plus (1000A Lithium Jump Starter)",
    brand: "NOCO",
    category: "Tools & Accessories",
    description: "1000-amp portable lithium jump starter for gasoline engines up to 6.0L and diesel up to 3.0L. Spark-proof technology with reverse polarity protection. Includes 100-lumen LED flashlight with 7 modes and USB charging port.",
    moq: "20 units",
    priceRange: "Contact for pricing",
    image: "tools",
    upc: "046221150025",
    sku: "GB40",
    specs: [
      { label: "Peak Current", value: "1000 Amps" },
      { label: "Engine Capacity", value: "Gas up to 6.0L / Diesel up to 3.0L" },
      { label: "Safety", value: "Spark-proof + reverse polarity protection" },
      { label: "Flashlight", value: "100-lumen LED with 7 modes" },
      { label: "USB Output", value: "Charges mobile devices on the go" },
      { label: "Battery", value: "Lithium-ion rechargeable" },
    ],
    features: ["1000A Peak", "Spark-Proof", "Reverse Polarity Safe", "LED Flashlight", "USB Power Bank"],
    certifications: ["UL", "FCC", "CE"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "kn-high-flow-33-2129",
    name: "K&N High-Flow Washable Air Filter",
    brand: "K&N",
    category: "Filters",
    description: "Drop-in replacement air filter with 4-6 layers of oiled cotton gauze between aluminum mesh. Designed to increase horsepower and acceleration by improving airflow. Washable and reusable for up to 50,000 miles before cleaning.",
    moq: "30 units",
    priceRange: "Contact for pricing",
    image: "filters",
    upc: "024844002340",
    sku: "33-2129",
    specs: [
      { label: "Material", value: "4-6 layers oiled cotton gauze, aluminum mesh" },
      { label: "Design", value: "Drop-in replacement for factory air box" },
      { label: "Benefit", value: "Increases horsepower and acceleration" },
      { label: "Maintenance", value: "Washable and reusable" },
      { label: "Service Life", value: "Up to 50,000 miles before cleaning" },
      { label: "Million Mile", value: "Backed by K&N Million Mile Limited Warranty" },
    ],
    features: ["Drop-In Replacement", "Washable & Reusable", "HP Gain", "Million Mile Warranty", "Aluminum Mesh Frame"],
    certifications: ["ISO 9001", "SAE"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "bosch-icon-26a",
    name: "Bosch ICON Wiper Blade (26\" - Driver Side)",
    brand: "Bosch",
    category: "Wipers",
    description: "Beam-style wiper blade with exclusive dual rubber compound resistant to heat and ozone cracking. Delivers up to 40% longer life than other premium blades. Integrated OE hook adapter for quick installation.",
    moq: "50 units",
    priceRange: "Contact for pricing",
    image: "wipers",
    upc: "028851528616",
    sku: "26A",
    specs: [
      { label: "Design", value: "Beam-type — no exposed metal frame" },
      { label: "Material", value: "Exclusive fx dual rubber compound" },
      { label: "Durability", value: "Up to 40% longer life vs. other premium blades" },
      { label: "Connector", value: "Integrated OE hook adapter" },
      { label: "Size", value: "26 inches (driver side)" },
      { label: "Weather Resistance", value: "Heat and ozone crack resistant" },
    ],
    features: ["Beam Design", "Dual Rubber Compound", "40% Longer Life", "OE Hook Adapter", "All-Weather Performance"],
    certifications: ["ISO 9001", "OE Spec"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "sparco-steering-cover-spc1113gr",
    name: "Sparco OPC Steering Wheel Cover (Black/Grey)",
    brand: "Sparco",
    category: "Racing & Interior",
    description: "Universal steering wheel cover combining high-quality synthetic leather and Alcantara-style suede. Ergonomic textured anti-slip grip for enhanced control and driving comfort. Embroidered Sparco logo.",
    moq: "40 units",
    priceRange: "Contact for pricing",
    image: "interior",
    upc: "8430046124403",
    sku: "SPC1113GR",
    specs: [
      { label: "Material", value: "Synthetic leather + Alcantara-look suede" },
      { label: "Fit", value: "Universal — 37 to 39 cm diameter wheels" },
      { label: "Grip", value: "Ergonomic textured anti-slip design" },
      { label: "Logo", value: "High-resistance embroidered Sparco badge" },
      { label: "Color", value: "Black / Grey" },
      { label: "Installation", value: "Slip-on with secure inner grip lining" },
    ],
    features: ["Alcantara-Look Suede", "Anti-Slip Grip", "Universal Fit", "Embroidered Logo", "Easy Slip-On"],
    certifications: ["ISO 9001"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "recaro-speed-seat-295071111",
    name: "Recaro Speed Sport Seat (Black Fabric / Red Stitching)",
    brand: "Recaro",
    category: "Seats",
    description: "Ergonomic reclining sport seat with millimeter-precise dual-side adjustment. Pronounced side bolsters for optimal lateral support in corners. Integrated harness slots for 3 or 4-point belts. Premium wear-resistant fabric.",
    moq: "6 units",
    priceRange: "Contact for pricing",
    image: "seats",
    upc: "638214000305",
    sku: "295.07.1111",
    specs: [
      { label: "Structure", value: "Reclining ergonomic backrest, dual-side adjustment" },
      { label: "Support", value: "Pronounced side bolsters for cornering" },
      { label: "Harness", value: "Integrated slots for 3 or 4-point belts" },
      { label: "Material", value: "Premium wear-resistant fabric, easy to clean" },
      { label: "Color", value: "Black with red contrast stitching" },
      { label: "Safety", value: "FIA homologation available on select models" },
    ],
    features: ["Reclining Backrest", "Side Bolster Support", "Harness Slots", "Wear-Resistant Fabric", "Racing Heritage"],
    certifications: ["FIA (select models)", "ISO 9001"],
    availability: "In Stock — Ships within 7 days",
  },
];

export const stats = [
  { label: "Part Numbers in Stock", value: "500+" },
  { label: "Top Brands Carried", value: "10+" },
  { label: "Order Turnaround", value: "24h" },
  { label: "Years in Business", value: "10+" },
];
