export interface Brand {
  id: string;
  name: string;
  category: string;
  logo: string;
  description: string;
}

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  description: string;
  moq: string;
  priceRange: string;
  image: string;
  upc: string;
  sku: string;
  specs: { label: string; value: string }[];
  features: string[];
  certifications: string[];
  availability: string;
}

export const brands: Brand[] = [
  { id: "weathertech", name: "WeatherTech", category: "Interior Accessories", logo: "WT", description: "Custom-fit floor liners, cargo liners, and vehicle protection products made in USA" },
  { id: "roam", name: "ROAM", category: "Tools & Accessories", logo: "RO", description: "Premium adventure coolers and rugged outdoor gear built for overlanding and off-road" },
  { id: "kn", name: "K&N", category: "Filters & Intake", logo: "KN", description: "High-performance washable air filters, intake systems, and filtration maintenance products" },
  { id: "anzo", name: "Anzo", category: "Lighting", logo: "AZ", description: "Premium LED lighting solutions — headlights, tail lights, and parking lights for trucks and SUVs" },
  { id: "stedi", name: "STEDI", category: "Lighting", logo: "ST", description: "High-output LED driving lights, light bars, and off-road illumination systems" },
  { id: "rugged-ridge", name: "Rugged Ridge", category: "Interior Accessories", logo: "RR", description: "Off-road interior accessories, floor mats, and Jeep-specific protection gear" },
  { id: "race-ramps", name: "Race Ramps", category: "Tools & Accessories", logo: "RA", description: "Lightweight composite ramps, wheel stands, and trailer accessories for shops and garages" },
  { id: "spectre", name: "Spectre", category: "Fluids & Lubricants", logo: "SP", description: "Performance air filter maintenance kits and cleaning solutions for reusable filters" },
  { id: "injen", name: "Injen", category: "Filters & Intake", logo: "IN", description: "High-performance cold air intake systems and cone filters for sport and muscle cars" },
  { id: "ovs", name: "OVS", category: "Roof Racks & Cargo", logo: "OV", description: "Overland Vehicle Systems — awnings, roof racks, and camping gear for trucks and SUVs" },
  { id: "ome", name: "Old Man Emu", category: "Suspension & Lift Kits", logo: "OM", description: "Premium suspension systems, lift kits, and shock absorbers for off-road and overland vehicles" },
  { id: "arb", name: "ARB", category: "Exterior Protection", logo: "AR", description: "Australian-built off-road protection, recovery gear, and vehicle accessories for overlanding" },
  { id: "toyota", name: "Toyota", category: "Engine Components", logo: "TY", description: "Genuine Toyota OEM parts and accessories engineered to exact factory specifications for fit and durability" },
  { id: "aftermarket", name: "Aftermarket", category: "Sensors & Electrical", logo: "AF", description: "High-quality compatible replacement sensors and electrical components meeting or exceeding OEM specifications" },
];

export const products: Product[] = [
  {
    id: "ovs-truck-awning-180129",
    name: "OVS Overland Truck Awning (6.5ft Side Mount — Black)",
    brand: "OVS",
    category: "Roof Racks & Cargo",
    description: "Heavy-duty 6.5-foot side-mount awning designed for trucks, SUVs, and overland rigs. Quick-deploy aluminum frame with waterproof 280G poly-cotton ripstop fabric. Provides 100+ sq ft of shade coverage. Includes mounting brackets for most roof rack systems.",
    moq: "8 units",
    priceRange: "Contact for pricing",
    image: "products/awning-truck.webp",
    upc: "850039048129",
    sku: "180129",
    specs: [
      { label: "Length", value: "6.5 ft (2.0 m) deployed" },
      { label: "Fabric", value: "280G poly-cotton ripstop, waterproof" },
      { label: "Frame", value: "Lightweight aluminum poles" },
      { label: "Mounting", value: "Universal roof rack brackets included" },
      { label: "Coverage", value: "100+ sq ft shade area" },
      { label: "Weight", value: "22 lbs (10 kg)" },
    ],
    features: ["Quick Deploy", "Waterproof Ripstop", "Aluminum Frame", "Universal Mount", "UV50+ Protection"],
    certifications: ["ISO 9001"],
    availability: "In Stock — Ships within 7 days",
  },
  {
    id: "roam-20l-cooler-20ldt",
    name: "ROAM Adventure Co. 20L Rugged Cooler (Slate Grey)",
    brand: "ROAM",
    category: "Tools & Accessories",
    description: "Premium 20-quart rotomolded cooler with up to 5-day ice retention. Features heavy-duty rubber latches, integrated drain plug, and non-slip feet. Built for overlanding, off-road, and marine environments.",
    moq: "12 units",
    priceRange: "Contact for pricing",
    image: "products/roam-cooler.webp",
    upc: "810028290104",
    sku: "20L-DT-SG",
    specs: [
      { label: "Capacity", value: "20 quarts (18.9 L) — holds 16 cans + ice" },
      { label: "Ice Retention", value: "Up to 5 days at 90°F" },
      { label: "Construction", value: "Rotomolded polyethylene" },
      { label: "Latches", value: "Heavy-duty rubber T-latches" },
      { label: "Drain", value: "Leak-resistant drain plug" },
      { label: "Color", value: "Slate Grey" },
    ],
    features: ["5-Day Ice Retention", "Rotomolded Shell", "Rubber T-Latches", "Leak-Proof Drain", "Non-Slip Feet"],
    certifications: ["ISO 9001"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "kn-filter-enclosure-rk3951",
    name: "K&N Air Filter Enclosure Kit (RK-3951)",
    brand: "K&N",
    category: "Filters & Intake",
    description: "Performance air filter enclosure with integrated heat shield and oiled cotton gauze filter. Designed to reduce intake temperatures and protect the filter element from engine bay heat. Bolt-on installation for select applications.",
    moq: "15 units",
    priceRange: "Contact for pricing",
    image: "products/kn-filter-enclosure.webp",
    upc: "024844039512",
    sku: "RK-3951",
    specs: [
      { label: "Filter Type", value: "Oiled cotton gauze, 4-6 layers" },
      { label: "Enclosure", value: "Integrated heat shield design" },
      { label: "Material", value: "Molded composite with aluminum mesh" },
      { label: "Benefit", value: "Reduces intake temps by up to 20°F" },
      { label: "Maintenance", value: "Washable and reusable" },
      { label: "Warranty", value: "K&N Million Mile Limited Warranty" },
    ],
    features: ["Heat Shield Enclosure", "Oiled Cotton Gauze", "Washable & Reusable", "Bolt-On Install", "Million Mile Warranty"],
    certifications: ["ISO 9001", "SAE"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "kn-intake-system-631147",
    name: "K&N Performance Air Intake System (63-1147)",
    brand: "K&N",
    category: "Filters & Intake",
    description: "Complete cold air intake system with high-flow filter, polyethylene intake tube, and custom heat shield. Engineered to increase horsepower and acceleration. Dyno-tested with guaranteed performance gains.",
    moq: "10 units",
    priceRange: "Contact for pricing",
    image: "products/kn-intake-system.webp",
    upc: "024844631147",
    sku: "63-1147",
    specs: [
      { label: "System Type", value: "Cold air intake with heat shield" },
      { label: "Tube", value: "High-density polyethylene" },
      { label: "Filter", value: "K&N oiled cotton gauze, conical" },
      { label: "HP Gain", value: "Dyno-proven gains — see application chart" },
      { label: "Installation", value: "Bolt-on, no tuning required" },
      { label: "Warranty", value: "10-year / Million Mile Limited" },
    ],
    features: ["Cold Air Design", "Dyno-Proven Gains", "No Tuning Required", "Bolt-On Install", "10-Year Warranty"],
    certifications: ["CARB EO", "ISO 9001"],
    availability: "In Stock — Ships within 7 days",
  },
  {
    id: "anzo-led-parking-311181",
    name: "Anzo LED Parking Light Assembly (Chrome / Amber)",
    brand: "Anzo",
    category: "Lighting",
    description: "Direct-fit replacement LED parking light assembly with clear chrome housing and amber reflector. Features ultra-bright SMD LEDs for enhanced visibility. DOT compliant and SAE approved. Sold as a pair.",
    moq: "20 pairs",
    priceRange: "Contact for pricing",
    image: "products/anzo-parking-lights.png",
    upc: "846959003119",
    sku: "311181",
    specs: [
      { label: "Housing", value: "Chrome with amber reflector" },
      { label: "LED Type", value: "Ultra-bright SMD LEDs" },
      { label: "Compliance", value: "DOT compliant, SAE approved" },
      { label: "Installation", value: "Plug-and-play, direct fit" },
      { label: "Sold As", value: "Pair (driver + passenger)" },
      { label: "Warranty", value: "1-year manufacturer warranty" },
    ],
    features: ["SMD LED Technology", "Chrome Housing", "Plug-and-Play", "DOT Compliant", "Direct Fit"],
    certifications: ["DOT", "SAE"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "stedi-type-x-pro-9inch",
    name: "STEDI Type-X Pro 9\" LED Driving Lights (Pair — Black)",
    brand: "STEDI",
    category: "Lighting",
    description: "Professional-grade 9-inch LED driving lights delivering 13,500 raw lumens per pair. Featuring Osram LED chips with spot and flood combo beam pattern. IP68 waterproof with heavy-duty stainless steel brackets. Includes black snap-on covers.",
    moq: "6 pairs",
    priceRange: "Contact for pricing",
    image: "products/stedi-driving-lights.png",
    upc: "9351693001518",
    sku: "ST9PRO-BLK",
    specs: [
      { label: "Output", value: "13,500 raw lumens per pair" },
      { label: "LED Chips", value: "Osram high-performance LEDs" },
      { label: "Beam Pattern", value: "Combo spot + flood" },
      { label: "Water Rating", value: "IP68 — dust and submersion proof" },
      { label: "Housing", value: "Aluminum with black finish" },
      { label: "Includes", value: "Snap-on covers, wiring harness, brackets" },
    ],
    features: ["13,500 Lumens", "Osram LEDs", "IP68 Waterproof", "Combo Beam", "Snap-On Covers"],
    certifications: ["IP68", "CE", "RoHS"],
    availability: "In Stock — Ships within 7 days",
  },
  {
    id: "rugged-ridge-floor-mats-12987",
    name: "Rugged Ridge All-Terrain Floor Mats (Front Pair — Black)",
    brand: "Rugged Ridge",
    category: "Interior Accessories",
    description: "Heavy-duty all-terrain floor mats with deep tread pattern to trap mud, water, and debris. Custom-fit for Jeep Wrangler JK/JL and select trucks. Made from durable thermoplastic rubber with nibbed backing to prevent shifting.",
    moq: "24 pairs",
    priceRange: "Contact for pricing",
    image: "products/rugged-ridge-mats.png",
    upc: "804314129870",
    sku: "12987.01",
    specs: [
      { label: "Fitment", value: "Jeep Wrangler JK/JL front pair" },
      { label: "Material", value: "Thermoplastic rubber (TPR)" },
      { label: "Tread Depth", value: "Deep chevron pattern" },
      { label: "Backing", value: "Nibbed anti-slip backing" },
      { label: "Protection", value: "Traps mud, water, sand, snow" },
      { label: "Color", value: "Black" },
    ],
    features: ["Deep Tread Pattern", "Anti-Slip Nibs", "All-Weather", "Jeep-Specific Fit", "Easy to Clean"],
    certifications: ["ISO 9001"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "weathertech-boottray-bt0734",
    name: "WeatherTech BootTray (Black — 36\" x 14\" x 1.5\")",
    brand: "WeatherTech",
    category: "Interior Accessories",
    description: "Versatile all-purpose tray with raised edges and ribbed design to contain spills, dirt, and moisture. Perfect for shop floors, entryways, and vehicle cargo areas. Made in USA from durable recycled plastic.",
    moq: "30 units",
    priceRange: "Contact for pricing",
    image: "products/weathertech-boottray.png",
    upc: "787765073400",
    sku: "BT0734",
    specs: [
      { label: "Dimensions", value: "36\" x 14\" x 1.5\" (91 x 36 x 4 cm)" },
      { label: "Material", value: "Recycled high-density plastic" },
      { label: "Design", value: "Ribbed surface with raised edges" },
      { label: "Usage", value: "Shop, entryway, cargo area" },
      { label: "Made In", value: "USA" },
      { label: "Weight", value: "3.2 lbs" },
    ],
    features: ["Raised Edges", "Ribbed Containment", "Recycled Plastic", "Made in USA", "Multi-Purpose"],
    certifications: ["ISO 9001"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "race-ramps-wheel-stands-rrws10",
    name: "Race Ramps Wheel Stands (10\" Rise — Pair)",
    brand: "Race Ramps",
    category: "Tools & Accessories",
    description: "Lightweight composite wheel stands with 10-inch rise for elevated vehicle maintenance. Supports up to 3,000 lbs per stand. Non-skid base and gentle approach angle. Ideal for brake jobs, wheel alignments, and undercarriage access.",
    moq: "8 pairs",
    priceRange: "Contact for pricing",
    image: "products/race-ramps-wheel-stands.png",
    upc: "899580002103",
    sku: "RR-WS-10",
    specs: [
      { label: "Rise Height", value: "10 inches (25.4 cm)" },
      { label: "Capacity", value: "3,000 lbs per stand (6,000 lbs pair)" },
      { label: "Material", value: "Lightweight composite foam core" },
      { label: "Base", value: "Non-skid textured surface" },
      { label: "Approach Angle", value: "Gentle 10.8° incline" },
      { label: "Weight", value: "12 lbs per stand" },
    ],
    features: ["10-Inch Rise", "3,000 lbs Capacity", "Lightweight Composite", "Non-Skid Base", "Gentle Approach"],
    certifications: ["ISO 9001"],
    availability: "In Stock — Ships within 7 days",
  },
  {
    id: "race-ramps-trailer-kicks-rrtsk",
    name: "Race Ramps Trailer Side Kicks (Pair — 5\" Rise)",
    brand: "Race Ramps",
    category: "Tools & Accessories",
    description: "Trailer wheel chock and ramp combo for safe trailer loading and unloading. 5-inch rise with integrated wheel stop. Fits trailer tires up to 30 inches. Lightweight composite construction won't damage trailer floors.",
    moq: "10 pairs",
    priceRange: "Contact for pricing",
    image: "products/race-ramps-trailer-kicks.png",
    upc: "899580002110",
    sku: "RR-TSK-5",
    specs: [
      { label: "Rise Height", value: "5 inches (12.7 cm)" },
      { label: "Tire Fit", value: "Up to 30-inch trailer tires" },
      { label: "Function", value: "Ramp + integrated wheel chock" },
      { label: "Material", value: "Lightweight composite" },
      { label: "Floor Safe", value: "Won't scratch or dent trailer decks" },
      { label: "Weight", value: "7 lbs per unit" },
    ],
    features: ["Ramp + Chock Combo", "5-Inch Rise", "Trailer-Safe", "Up to 30\" Tires", "Lightweight"],
    certifications: ["ISO 9001"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "kn-filter-minder-e1ac",
    name: "K&N Filter Minder Air Filter Gauge",
    brand: "K&N",
    category: "Filters & Intake",
    description: "Precision air filter restriction gauge that mounts directly to the filter housing. Color-coded dial indicates when cleaning is needed — green for clean, yellow for caution, red for service required. Push-button reset after maintenance.",
    moq: "40 units",
    priceRange: "Contact for pricing",
    image: "products/kn-filter-minder.png",
    upc: "024844000145",
    sku: "85-0100",
    specs: [
      { label: "Function", value: "Air filter restriction indicator" },
      { label: "Dial", value: "Color-coded: green / yellow / red" },
      { label: "Mounting", value: "Mounts to filter housing" },
      { label: "Reset", value: "Push-button manual reset" },
      { label: "Compatibility", value: "Universal for K&N and standard filters" },
      { label: "Housing", value: "Impact-resistant clear plastic" },
    ],
    features: ["Color-Coded Gauge", "Push-Button Reset", "Universal Mount", "Impact-Resistant", "Maintenance Alert"],
    certifications: ["ISO 9001"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "kn-dryflow-cleaner-99621",
    name: "K&N Dryflow Heavy Duty Air Filter Cleaner (1 Gallon)",
    brand: "K&N",
    category: "Fluids & Lubricants",
    description: "Professional-grade degreaser formulated specifically for K&N Dryflow synthetic air filters. Removes dirt, dust, and grime without damaging the filter media. Includes spray applicator for even coverage. Biodegradable formula.",
    moq: "24 gallons",
    priceRange: "Contact for pricing",
    image: "products/kn-dryflow-cleaner.png",
    upc: "024844099621",
    sku: "99-0621",
    specs: [
      { label: "Volume", value: "1 gallon (3.78 L)" },
      { label: "Formula", value: "Biodegradable degreaser" },
      { label: "For Use On", value: "K&N Dryflow synthetic filters" },
      { label: "Application", value: "Spray-on, rinse-off" },
      { label: "Includes", value: "Spray applicator wand" },
      { label: "Safe For", value: "All filter media types" },
    ],
    features: ["Biodegradable", "Spray Applicator", "Deep Cleans", "Filter-Safe", "1 Gallon Size"],
    certifications: ["ISO 9001"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "kn-recharger-kit-990500",
    name: "K&N Recharger Air Filter Cleaning Kit",
    brand: "K&N",
    category: "Fluids & Lubricants",
    description: "Complete service kit for K&N oiled cotton gauze air filters. Includes 12 oz Power Kleen cleaner and 6.5 oz red aerosol filter oil. Restores filter to like-new condition. Enough for 5-7 cleanings.",
    moq: "30 kits",
    priceRange: "Contact for pricing",
    image: "products/kn-recharger-kit.png",
    upc: "024844099050",
    sku: "99-5050",
    specs: [
      { label: "Contents", value: "Power Kleen cleaner (12 oz) + Filter Oil (6.5 oz)" },
      { label: "Cleaner", value: "Power Kleen degreaser spray" },
      { label: "Oil", value: "Red aerosol filter oil" },
      { label: "Yield", value: "5-7 filter cleanings per kit" },
      { label: "For Use On", value: "All K&N oiled cotton gauze filters" },
      { label: "Type", value: "Aerosol oil + liquid cleaner" },
    ],
    features: ["Complete Kit", "Aerosol Oil", "Power Kleen", "5-7 Cleanings", "Restores Performance"],
    certifications: ["ISO 9001"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "spectre-cleaning-kit-884820",
    name: "Spectre AccuCharge Air Filter Cleaning Kit",
    brand: "Spectre",
    category: "Fluids & Lubricants",
    description: "Precision cleaning kit for Spectre and other reusable cone and panel air filters. Includes 12 oz cleaner and 8 oz performance filter oil with measured gradations for exact oil application. Fast and easy 3-step process.",
    moq: "25 kits",
    priceRange: "Contact for pricing",
    image: "products/spectre-cleaning-kit.png",
    upc: "089258848201",
    sku: "884820",
    specs: [
      { label: "Contents", value: "Filter cleaner (12 oz) + Filter oil (8 oz)" },
      { label: "Oil Gradations", value: "Measured markings for precise application" },
      { label: "Process", value: "3-step: clean, rinse, oil" },
      { label: "For Use On", value: "Spectre and all reusable filters" },
      { label: "Application", value: "Spray-on cleaner, oil with gradations" },
      { label: "Type", value: "Liquid cleaner + liquid oil" },
    ],
    features: ["AccuCharge Gradations", "3-Step Process", "Precise Oil Application", "Universal Fit", "Complete Kit"],
    certifications: ["ISO 9001"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "injen-cone-filter-x1013",
    name: "Injen High Performance Cone Air Filter (Red — 3.0\")",
    brand: "Injen",
    category: "Filters & Intake",
    description: "SuperNano-Web dry synthetic cone air filter with 3.0-inch inlet. Delivers maximum airflow with superior filtration efficiency. No oil required — clean with compressed air or tap water. Deep pleats increase surface area.",
    moq: "20 units",
    priceRange: "Contact for pricing",
    image: "products/injen-air-filter.png",
    upc: "843131000131",
    sku: "X-1013-BR",
    specs: [
      { label: "Type", value: "Dry synthetic SuperNano-Web" },
      { label: "Inlet", value: "3.0 inches (76 mm)" },
      { label: "Media", value: "No oil required — dry filter" },
      { label: "Cleaning", value: "Compressed air or tap water" },
      { label: "Color", value: "Red filter media, black base" },
      { label: "Design", value: "Deep-pleat for max surface area" },
    ],
    features: ["SuperNano-Web", "Dry Synthetic", "No Oil Required", "Deep Pleats", "3.0\" Inlet"],
    certifications: ["ISO 9001"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "kn-high-flow-33-2129",
    name: "K&N High-Flow Washable Air Filter (Drop-In Replacement)",
    brand: "K&N",
    category: "Filters & Intake",
    description: "Drop-in replacement air filter with 4-6 layers of oiled cotton gauze between aluminum mesh. Designed to increase horsepower and acceleration by improving airflow. Washable and reusable for up to 50,000 miles before cleaning.",
    moq: "30 units",
    priceRange: "Contact for pricing",
    image: "products/kn-air-filter.png",
    upc: "024844002340",
    sku: "33-2129",
    specs: [
      { label: "Material", value: "4-6 layers oiled cotton gauze, aluminum mesh" },
      { label: "Design", value: "Drop-in replacement for factory air box" },
      { label: "Benefit", value: "Increases horsepower and acceleration" },
      { label: "Maintenance", value: "Washable and reusable" },
      { label: "Service Life", value: "Up to 50,000 miles before cleaning" },
      { label: "Warranty", value: "K&N Million Mile Limited Warranty" },
    ],
    features: ["Drop-In Replacement", "Washable & Reusable", "HP Gain", "Million Mile Warranty", "Aluminum Mesh Frame"],
    certifications: ["ISO 9001", "SAE"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "weathertech-floorliner-444751",
    name: "WeatherTech FloorLiner DigitalFit (Front Row — Black)",
    brand: "WeatherTech",
    category: "Interior Accessories",
    description: "Laser-measured floor liners with advanced surface channels that trap fluids, mud, and debris. Custom-fit for Ford F-150 (select cab models). Made in USA from patented high-density thermoplastic.",
    moq: "20 sets",
    priceRange: "Contact for pricing",
    image: "products/weathertech-liner.jpg",
    upc: "787765362145",
    sku: "444751",
    specs: [
      { label: "Compatibility", value: "Ford F-150 (select cab models)" },
      { label: "Material", value: "Patented high-density TPO thermoplastic" },
      { label: "Design", value: "Advanced channels retain fluids, mud, and sand" },
      { label: "Fit", value: "Digital laser measurement for perfect floor coverage" },
      { label: "Color", value: "Black" },
      { label: "Made In", value: "USA" },
    ],
    features: ["Digital Laser Fit", "Advanced Channel Design", "High-Density TPO", "Made in USA", "All-Weather Protection"],
    certifications: ["ISO 9001", "OE Spec"],
    availability: "In Stock — Ships within 5 days",
  },
  {
    id: "ome-mt64-tacoma-3in-1119k",
    name: "Old Man Emu MT64 3\" Lift Kit w/UCA for Tacoma (2024+)",
    brand: "Old Man Emu",
    category: "Suspension & Lift Kits",
    description: "Complete 3-inch suspension lift kit for 2024+ Toyota Tacoma featuring MT64 monotube shocks with 64mm bore, front upper control arms (UCA), and matched coil springs. Front rated 220-330 lbs / Rear 0 lbs. Delivers exceptional off-road articulation and on-road comfort with consistent damping across temperature extremes.",
    moq: "4 kits",
    priceRange: "Contact for pricing",
    image: "products/old-man-emu-mt64-lift-kit.jpg",
    upc: "931714401119",
    sku: "MT64-1119K",
    specs: [
      { label: "Lift Height", value: "3 inches (front) / 2 inches (rear)" },
      { label: "Front Rate", value: "220-330 lbs constant load" },
      { label: "Rear Rate", value: "0 lbs (no additional load)" },
      { label: "Shock Type", value: "MT64 monotube, 64mm bore" },
      { label: "Includes", value: "4 shocks + 2 UCA + front/rear springs" },
      { label: "Fitment", value: "Toyota Tacoma 2024+ (3rd gen facelift)" },
    ],
    features: ["MT64 Monotube Shocks", "Upper Control Arms", "64mm Bore", "Constant Load Tuned", "Bolt-On Install"],
    certifications: ["ISO 9001", "TUV"],
    availability: "In Stock — Ships within 7 days",
  },
  {
    id: "arb-summit-side-step-4421175k1",
    name: "ARB Summit Side Step and Rail Kit (Black)",
    brand: "ARB",
    category: "Exterior Protection",
    description: "Heavy-duty tubular steel side step and rail protection system designed for off-road and overland vehicles. Provides rocker panel protection and convenient step access. Powder-coated black finish for corrosion resistance. Vehicle-specific mounting brackets included.",
    moq: "6 kits",
    priceRange: "Contact for pricing",
    image: "products/arb-summit-side-step.jpg",
    upc: "932202800442",
    sku: "4421175K1",
    specs: [
      { label: "Material", value: "Tubular steel with powder-coated black finish" },
      { label: "Function", value: "Rocker panel protection + step access" },
      { label: "Finish", value: "Black powder coat, corrosion resistant" },
      { label: "Mounting", value: "Vehicle-specific bolt-on brackets" },
      { label: "Design", value: "Summit series — heavy-duty off-road rated" },
      { label: "Includes", value: "Left + right side steps, rails, mounting hardware" },
    ],
    features: ["Rocker Panel Protection", "Step Access", "Powder-Coated Steel", "Bolt-On Install", "Off-Road Rated"],
    certifications: ["ISO 9001"],
    availability: "In Stock — Ships within 7 days",
  },
  {
    id: "toyota-timing-belt-13568yzz03",
    name: "Genuine OEM Engine Timing Belt For Toyota Tacoma, 4Runner, Tundra",
    brand: "Toyota",
    category: "Engine Components",
    description: "Genuine Toyota OEM engine timing belt (camshaft drive belt) for select Tacoma, 4Runner, and Tundra models. Manufactured by Toyota's OEM supplier to exact factory specifications for precise timing, long service life, and reliable performance. Made in Japan.",
    moq: "10 belts",
    priceRange: "Contact for pricing",
    image: "products/toyota-timing-belt.webp",
    upc: "TOY-13568YZZ03",
    sku: "13568-YZZ03",
    specs: [
      { label: "OEM Number", value: "13568-YZZ03" },
      { label: "Application", value: "Toyota Tacoma, 4Runner, Tundra" },
      { label: "Type", value: "Engine timing belt / camshaft drive belt" },
      { label: "Material", value: "Reinforced rubber with high-strength fiber cords" },
      { label: "Origin", value: "Made in Japan" },
      { label: "Condition", value: "New, genuine OEM" },
    ],
    features: ["Genuine Toyota OEM", "Exact Factory Specs", "Made in Japan", "Long Service Life", "Precision Timing"],
    certifications: ["ISO 9001", "TS 16949"],
    availability: "In Stock — Ships within 3 days",
  },
  {
    id: "nissan-maf-sensor-murano",
    name: "Mass Air Flow Sensor \u2014 Compatible with Nissan Murano (2003\u20132007, 2009\u20132014)",
    brand: "Aftermarket",
    category: "Sensors & Electrical",
    description: "Direct-fit replacement mass air flow (MAF) sensor compatible with 2003\u20132007 and 2009\u20132014 Nissan Murano models. Measures intake air volume and temperature to optimize fuel injection and ignition timing. Precise OEM-style connector and calibration for reliable engine performance and emissions compliance.",
    moq: "12 sensors",
    priceRange: "Contact for pricing",
    image: "products/nissan-maf-sensor.webp",
    upc: "NIS-MAF-MURANO-03-14",
    sku: "AF-MAF-NIS-MUR",
    specs: [
      { label: "Application", value: "Nissan Murano 2003\u20132007, 2009\u20132014" },
      { label: "Type", value: "Mass Air Flow (MAF) Sensor" },
      { label: "Connector", value: "OEM-style 5-pin plug" },
      { label: "Housing", value: "Molded polymer with brass sensing element" },
      { label: "Calibration", value: "Pre-calibrated for direct replacement" },
      { label: "Warranty", value: "2-year limited warranty" },
    ],
    features: ["Direct OEM Replacement", "Plug-and-Play Install", "Pre-Calibrated", "Brass Sensing Element", "Emissions Compliant"],
    certifications: ["ISO 9001", "TS 16949"],
    availability: "In Stock \u2014 Ships within 5 days",
  },
];

export const stats = [
  { label: "Part Numbers in Stock", value: "500+" },
  { label: "Top Brands Carried", value: "14+" },
  { label: "Order Turnaround", value: "24h" },
  { label: "Years in Business", value: "10+" },
];
