export interface Brand {
  id: string;
  name: string;
  category: string;
  logo: string;
  description: string;
}

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: string;
  description: string;
  moq: string;
  priceRange: string;
  image: string;
  upc: string;
  sku: string;
  specs: { label: string; value: string }[];
  features: string[];
  certifications: string[];
  availability: string;
}

export const brands: Brand[] = [
  { id: "sony", name: "Sony", category: "Electronics", logo: "S", description: "Consumer electronics, gaming, and entertainment products" },
  { id: "samsung", name: "Samsung", category: "Electronics", logo: "SA", description: "Smartphones, TVs, home appliances, and semiconductors" },
  { id: "apple", name: "Apple", category: "Electronics", logo: "A", description: "Premium consumer electronics and software" },
  { id: "nike", name: "Nike", category: "Apparel", logo: "N", description: "Athletic footwear, apparel, and equipment" },
  { id: "adidas", name: "Adidas", category: "Apparel", logo: "AD", description: "Sports footwear, apparel, and accessories" },
  { id: "lego", name: "LEGO", category: "Toys", logo: "L", description: "Construction toys and educational products" },
  { id: "hasbro", name: "Hasbro", category: "Toys", logo: "H", description: "Board games, toys, and entertainment products" },
  { id: "loreal", name: "L'Oréal", category: "Beauty", logo: "LO", description: "Cosmetics, skincare, and hair care products" },
  { id: "procter", name: "P&G", category: "Household", logo: "PG", description: "Consumer goods and personal care products" },
  { id: "unilever", name: "Unilever", category: "Household", logo: "U", description: "Food, beverages, and personal care products" },
  { id: "philips", name: "Philips", category: "Electronics", logo: "P", description: "Healthcare, lighting, and consumer electronics" },
  { id: "canon", name: "Canon", category: "Electronics", logo: "C", description: "Cameras, printers, and imaging equipment" },
];

export const products: Product[] = [
  {
    id: "acer-nitro-v15",
    name: "Acer Nitro V 15 (15.6\" Full HD, 144Hz)",
    brand: "ACER",
    category: "Electronics",
    description: "Laptop gaming de alto rendimiento con AMD Ryzen 7 y NVIDIA RTX 4060. Ideal para distribuidores de tecnología enfocados en el mercado gamer.",
    moq: "10 units",
    priceRange: "Contact for pricing",
    image: "laptop",
    upc: "195133242097",
    sku: "NH.QPDAA.001",
    specs: [
      { label: "Procesador", value: "AMD Ryzen 7 7735HS (8 núcleos, hasta 4.75 GHz)" },
      { label: "Memoria RAM", value: "16 GB DDR5" },
      { label: "Almacenamiento", value: "1 TB SSD PCIe Gen 4 NVMe" },
      { label: "Tarjeta Gráfica", value: "NVIDIA GeForce RTX 4060 (8 GB GDDR6)" },
      { label: "Pantalla", value: "15.6\" Full HD (1920×1080) IPS, 144Hz" },
      { label: "Sistema Operativo", value: "Windows 11 Home" },
    ],
    features: ["RTX 4060 Gaming GPU", "144Hz IPS Display", "16 GB DDR5 RAM", "1 TB NVMe SSD", "Win 11 Home"],
    certifications: ["FCC", "CE", "RoHS", "Energy Star"],
    availability: "In Stock — Ships within 10 days",
  },
  {
    id: "samsung-s24-ultra",
    name: "Samsung Galaxy S24 Ultra (256GB - Gris Titanio)",
    brand: "SAMSUNG",
    category: "Electronics",
    description: "Smartphone flagship con cámara de 200MP, S Pen integrado y funciones de IA avanzadas. Alta demanda en toda Latinoamérica.",
    moq: "20 units",
    priceRange: "Contact for pricing",
    image: "smartphone",
    upc: "8806095309446",
    sku: "SM-S928BZTGEUBF",
    specs: [
      { label: "Pantalla", value: "6.8\" Dynamic AMOLED 2X, QHD+ (3120×1440)" },
      { label: "Procesador", value: "Qualcomm Snapdragon 8 Gen 3 Octa-Core" },
      { label: "RAM / Almacenamiento", value: "12 GB RAM + 256 GB interno" },
      { label: "Cámaras", value: "200 MP + 50 MP + 12 MP + 10 MP (IA)" },
      { label: "Batería", value: "5000 mAh, carga rápida e inalámbrica" },
      { label: "Protección", value: "IP68 + S Pen integrado" },
    ],
    features: ["200MP Quad Camera System", "6.8\" QHD+ AMOLED", "S Pen Built-in", "Galaxy AI", "IP68 Water Resistance"],
    certifications: ["FCC", "CE", "IC", "IP68"],
    availability: "In Stock — Ships within 10 days",
  },
  {
    id: "stihl-ms250",
    name: "Motosierra de Gasolina Profesional STIHL MS 250",
    brand: "STIHL",
    category: "Tools & Equipment",
    description: "Motosierra profesional de gasolina con alto rendimiento y sistema de filtrado de larga duración. Referente en el mercado de herramientas forestales.",
    moq: "5 units",
    priceRange: "Contact for pricing",
    image: "tools",
    upc: "795711122114",
    sku: "1123 011 3074",
    specs: [
      { label: "Cilindrada", value: "45.4 cc (2.77 cu. in.)" },
      { label: "Potencia del Motor", value: "2.3 kW (3.0 bhp)" },
      { label: "Capacidad de Combustible", value: "470 cc (15.9 oz.)" },
      { label: "Longitud de Espada", value: "18 pulgadas (45 cm)" },
      { label: "Peso del Cabezal", value: "4.6 kg (10.1 lbs)" },
      { label: "Sistema de Filtrado", value: "Larga duración con compensador integrado" },
    ],
    features: ["45.4cc Engine", "18\" Recommended Bar", "3.0 bhp Power Output", "Long-Life Filter System", "Professional Grade"],
    certifications: ["EPA", "CARB", "CE"],
    availability: "In Stock — Ships within 7 days",
  },
  {
    id: "jbl-flip6",
    name: "JBL Flip 6 (Altavoz Bluetooth Impermeable - Negro)",
    brand: "JBL",
    category: "Electronics",
    description: "Altavoz Bluetooth portátil con 20W de potencia, PartyBoost y certificación IP67. Bestseller en el segmento de audio portable.",
    moq: "50 units",
    priceRange: "Contact for pricing",
    image: "speaker",
    upc: "6925281993121",
    sku: "JBLFLIP6BLKAMF",
    specs: [
      { label: "Potencia de Salida", value: "20W RMS (graves) + 10W RMS (agudos)" },
      { label: "Respuesta de Frecuencia", value: "63 Hz – 20 kHz" },
      { label: "Conectividad", value: "Bluetooth 5.1 + PartyBoost" },
      { label: "Duración de Batería", value: "Hasta 12 horas (4800 mAh)" },
      { label: "Resistencia", value: "IP67 — Impermeable y hermético al polvo" },
    ],
    features: ["30W Total Power", "IP67 Waterproof", "Bluetooth 5.1", "PartyBoost", "12h Battery"],
    certifications: ["FCC", "CE", "IP67"],
    availability: "In Stock — Ships within 7 days",
  },
  {
    id: "vizio-v505",
    name: "VIZIO V-Series 50\" Class 4K HDR Smart TV",
    brand: "VIZIO",
    category: "Electronics",
    description: "Smart TV 4K de 50\" con Dolby Vision, SmartCast y compatibilidad con AirPlay y Chromecast. Excelente relación calidad-precio para distribuidores.",
    moq: "10 units",
    priceRange: "Contact for pricing",
    image: "tv",
    upc: "845226018381",
    sku: "V505-J09",
    specs: [
      { label: "Tamaño de Pantalla", value: "50\" (49.5\" en diagonal)" },
      { label: "Resolución", value: "4K Ultra HD (3840×2160)" },
      { label: "HDR", value: "Dolby Vision, HDR10+, HDR10, HLG" },
      { label: "Procesador", value: "IQ Active Processor" },
      { label: "Smart TV", value: "SmartCast + Apple AirPlay + Chromecast" },
      { label: "Puertos", value: "3× HDMI 2.1, 1× USB, Ethernet, Óptico" },
    ],
    features: ["50\" 4K UHD Display", "Dolby Vision & HDR10+", "SmartCast Platform", "AirPlay & Chromecast", "3× HDMI 2.1"],
    certifications: ["FCC", "CE", "Energy Star"],
    availability: "In Stock — Ships within 14 days",
  },
  {
    id: "babyliss-nano-titanium",
    name: "Plancha Alaciadora BaBylissPRO Nano Titanium 1¼\"",
    brand: "BABYLISS",
    category: "Beauty & Grooming",
    description: "Plancha profesional de Nano Titanio con calentamiento cerámico instantáneo hasta 450°F. Referente en salones profesionales de todo el continente.",
    moq: "30 units",
    priceRange: "Contact for pricing",
    image: "beauty",
    upc: "074108215320",
    sku: "BABNT2091T",
    specs: [
      { label: "Placas", value: "Nano Titanium puras de 1.25 pulgadas" },
      { label: "Temperatura Máxima", value: "232°C (450°F) — ajuste digital" },
      { label: "Tecnología de Calentamiento", value: "Calentador cerámico instantáneo" },
      { label: "Cable", value: "Giratorio 360 grados" },
      { label: "Carcasa", value: "Ryton resistente a altas temperaturas" },
    ],
    features: ["Nano Titanium Plates", "Up to 450°F", "Instant Ceramic Heater", "360° Swivel Cord", "Professional Grade"],
    certifications: ["UL", "CE", "ETL"],
    availability: "In Stock — Ships within 7 days",
  },
  {
    id: "babyliss-goldfx",
    name: "Cortadora Profesional BaBylissPRO GoldFX Lithium Clipper",
    brand: "BABYLISS",
    category: "Beauty & Grooming",
    description: "Cortadora con motor Ferrari sin escobillas a 9500 RPM y cuchilla DLC/Ni-Ti. Estándar de oro en barberías profesionales.",
    moq: "20 units",
    priceRange: "Contact for pricing",
    image: "beauty",
    upc: "074108383340",
    sku: "FX870G",
    specs: [
      { label: "Motor", value: "Ferrari brushless de alto torque" },
      { label: "Velocidad", value: "9500 RPM" },
      { label: "Cuchilla", value: "Acero inoxidable con revestimiento DLC/Ni-Ti" },
      { label: "Batería", value: "Iones de litio — 2 horas inalámbrico" },
      { label: "Carcasa", value: "Completamente metálica, mango estriado" },
    ],
    features: ["Ferrari Brushless Motor", "9500 RPM", "DLC/Ni-Ti Fade Blade", "2h Wireless Runtime", "Full Metal Body"],
    certifications: ["UL", "CE", "FCC"],
    availability: "In Stock — Ships within 7 days",
  },
  {
    id: "gillette-labs",
    name: "Gillette Labs con Barra Exfoliante (Mango Metálico + Base Magnética)",
    brand: "GILLETTE",
    category: "Beauty & Grooming",
    description: "Sistema de afeitado premium con barra exfoliante integrada, tecnología FlexDisc 2D y base magnética. Producto de alta gama con margen superior.",
    moq: "100 units",
    priceRange: "Contact for pricing",
    image: "beauty",
    upc: "047400673328",
    sku: "80362369",
    specs: [
      { label: "Tecnología del Mango", value: "Barra exfoliante integrada" },
      { label: "Eje de Movimiento", value: "FlexDisc 2D — se adapta al contorno" },
      { label: "Cartucho de Hojas", value: "5 hojas ultra finas con antifricción" },
      { label: "Soporte", value: "Base magnética premium" },
      { label: "Material del Mango", value: "Metal premium" },
    ],
    features: ["Integrated Exfoliating Bar", "FlexDisc 2D Pivot", "5 Anti-Friction Blades", "Magnetic Stand", "Premium Metal Handle"],
    certifications: ["FDA", "CE"],
    availability: "In Stock — Ships within 7 days",
  },
  {
    id: "dewalt-drill-dcd771c2",
    name: "Kit de Taladro/Atornillador Compacto DEWALT 20V MAX ½\"",
    brand: "DEWALT",
    category: "Tools & Equipment",
    description: "Kit completo de taladro compacto 20V MAX con 2 baterías, cargador y bolsa. Solución todo-en-uno para contratistas y distribuidores de herramientas.",
    moq: "10 units",
    priceRange: "Contact for pricing",
    image: "tools",
    upc: "885911325905",
    sku: "DCD771C2",
    specs: [
      { label: "Voltaje", value: "20V MAX*" },
      { label: "Broquero (Chuck)", value: "½\" manga única de trinquete (sin llave)" },
      { label: "Velocidades", value: "2 rangos: 0–450 RPM y 0–1500 RPM" },
      { label: "Potencia Máxima", value: "300 UWO (Unit Watts Out)" },
      { label: "Contenido del Kit", value: "Taladro + 2 baterías 1.3Ah + cargador + bolsa" },
    ],
    features: ["20V MAX Platform", "300 UWO Power", "2-Speed Mechanical", "½\" Keyless Chuck", "Kit with 2 Batteries"],
    certifications: ["UL", "CE", "CSA"],
    availability: "In Stock — Ships within 7 days",
  },
  {
    id: "dewalt-circular-dcs391b",
    name: "Sierra Circular Inalámbrica DEWALT 20V MAX 6½\" (Solo herramienta)",
    brand: "DEWALT",
    category: "Tools & Equipment",
    description: "Sierra circular inalámbrica 20V MAX con 5150 RPM y zapata de magnesio. Ideal para contratistas que requieren potencia sin cables.",
    moq: "10 units",
    priceRange: "Contact for pricing",
    image: "tools",
    upc: "885911244763",
    sku: "DCS391B",
    specs: [
      { label: "Velocidad del Motor", value: "5150 RPM" },
      { label: "Capacidad de Biselado", value: "0° a 50°" },
      { label: "Profundidad de Corte (90°)", value: "2¼ pulgadas" },
      { label: "Diámetro del Disco", value: "6½\" con zapata de magnesio" },
      { label: "Peso", value: "7.1 lbs (3.2 kg)" },
    ],
    features: ["5150 RPM Motor", "0–50° Bevel Capacity", "2¼\" Cut Depth", "Magnesium Shoe", "20V MAX Platform"],
    certifications: ["UL", "CE", "CSA"],
    availability: "In Stock — Ships within 7 days",
  },
];

export const stats = [
  { label: "Brands Represented", value: "120+" },
  { label: "Annual Volume", value: "$50M+" },
  { label: "Countries Served", value: "35" },
  { label: "Years Experience", value: "15" },
];
